### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by shaded3d** [AlexisTheLarge/faceset-builder#1] opened 2018-03-07 19:44 UTC
Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.C:\Windows\system32>cd ..C:\Windows>cd ..C:\>cd ProgramsC:\Programs>cd faceset-builderC:\Programs\faceset-builder>python faceset-builder.py collect D:\1\A\b D:\1\A D:\1\A\exEncoding reference faces...0%|                                                    | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):File "faceset-builder.py", line 5, in <module>faceset_builder()File "C:\Python35\lib\site-packages\click\core.py", line 722, in __call__return self.main(*args, **kwargs)File "C:\Python35\lib\site-packages\click\core.py", line 697, in mainrv = self.invoke(ctx)File "C:\Python35\lib\site-packages\click\core.py", line 1066, in invokereturn _process_result(sub_ctx.command.invoke(sub_ctx))File "C:\Python35\lib\site-packages\click\core.py", line 895, in invokereturn ctx.invoke(self.callback, **ctx.params)File "C:\Python35\lib\site-packages\click\core.py", line 535, in invokereturn callback(*args, **kwargs)File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 172, in collectcollector(**kwargs)File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 95, in collectorface_encodings = encodeFaces(kwargs['reference_dir'])File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 39, in encodeFacestarget_face = face_recognition.face_encodings(face_recognition.load_image_file(os.path.join(face_dir, file)))File "C:\Python35\lib\site-packages\face_recognition\api.py", line 84, in load_image_filereturn scipy.misc.imread(file, mode=mode)File "C:\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfuncreturn func(*args, **kwds)File "C:\Python35\lib\site-packages\scipy\misc\pilutil.py", line 164, in imreadim = Image.open(name)File "C:\Python35\lib\site-packages\PIL\Image.py", line 2543, in openfp = builtins.open(filename, "rb")PermissionError: [Errno 13] Permission denied: 'D:\\1\\A\\aligned'C:\Programs\faceset-builder>python faceset-builder.py collect D:\1\A\b D:\1\A D:\1\A\exEncoding reference faces...0%|                                                    | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):File "faceset-builder.py", line 5, in <module>faceset_builder()File "C:\Python35\lib\site-packages\click\core.py", line 722, in __call__return self.main(*args, **kwargs)File "C:\Python35\lib\site-packages\click\core.py", line 697, in mainrv = self.invoke(ctx)File "C:\Python35\lib\site-packages\click\core.py", line 1066, in invokereturn _process_result(sub_ctx.command.invoke(sub_ctx))File "C:\Python35\lib\site-packages\click\core.py", line 895, in invokereturn ctx.invoke(self.callback, **ctx.params)File "C:\Python35\lib\site-packages\click\core.py", line 535, in invokereturn callback(*args, **kwargs)File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 172, in collectcollector(**kwargs)File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 95, in collectorface_encodings = encodeFaces(kwargs['reference_dir'])File "C:\Programs\faceset-builder\faceset_builder\faceset_builder.py", line 39, in encodeFacestarget_face = face_recognition.face_encodings(face_recognition.load_image_file(os.path.join(face_dir, file)))File "C:\Python35\lib\site-packages\face_recognition\api.py", line 84, in load_image_filereturn scipy.misc.imread(file, mode=mode)File "C:\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfuncreturn func(*args, **kwds)File "C:\Python35\lib\site-packages\scipy\misc\pilutil.py", line 164, in imreadim = Image.open(name)File "C:\Python35\lib\site-packages\PIL\Image.py", line 2543, in openfp = builtins.open(filename, "rb")PermissionError: [Errno 13] Permission denied: 'D:\\1\\A\\aligned'C:\Programs\faceset-builder>C:\Programs\faceset-builder>

Any idea what could be the problem here?

**Comment by AlexisTheLarge** [comment] 2018-03-07 21:03
I haven't tested this script on Windows, so I don't know if it's compatible. But I think this is an error that might be remedied by simply running the command prompt as administrator.

**Comment by shaded3d** [comment] 2018-03-07 21:09
Tried that, no change. It looks like a ffmpeg error, right?

**Comment by AlexisTheLarge** [comment] 2018-03-07 21:22
It looks like it's having trouble opening the images due to insufficient permission. The only thing I can think of is running as administrator, or maybe you need to take ownership over the folders your images are in?

**Comment by shaded3d** [comment] 2018-03-07 22:04
Tried admin and taking ownership, no luck.

**Comment by AlexisTheLarge** [comment] 2018-03-07 22:42
Oh. I think I know what the problem is. The script is trying to open the folder D:\1\A\aligned as an image.

But I'd expect to get an IsADirectoryError from that so can you just check if using a reference folder with only images and no folders works?

**Comment by shaded3d** [comment] 2018-03-08 08:18
Hey, that worked! Great catch. I guess this is resolved now.

**Comment by shaded3d** [comment] 2018-03-08 08:19
Btw, any idea why it's taking so long to extract? Is it utilizing the CPU?

**Comment by AlexisTheLarge** [comment] 2018-03-08 12:07
Please open a new issue for that. I'm closing this with my next commit.

And please provide the following:

- Computer specs
- How many files in <reference_dir>
- if you're extracting form images, how many images, and how long it takes to process all images.
- if you're extracting from videos: (resolution, duration ,etc) and how long that file takes to process.
- The exact command you are running. I need to know what options you're using.

**Closed as completed** 2018-03-08 12:08 UTC
Labels: bug
